# Generated by Cloud66 Starter

FROM httpd:latest
FROM node:4.6

EXPOSE 5000

ENV APP_HOME /app
RUN mkdir -pv $APP_HOME
WORKDIR $APP_HOME

ADD . $APP_HOME

ENV NODE_ENV production
ENV NPM_CONFIG_LOGLEVEL warn

# Copy files and directories from the application
COPY server.js /usr/local/apache2/htdocs/
COPY app/ /usr/local/apache2/htdocs/app/

# ADD CUSTOM REGISTRY HERE IF REQUIRED
# ENV CUSTOM_REGISTRY https://registry.npmjs.org/ 
# RUN npm config set strict-ssl false
# RUN npm config set registry $CUSTOM_REGISTRY

RUN npm install
